### ISSUE TITLE
mo money mo problems

### ISSUE THREAD

**Issue by neeilan** [AaruranLog/rl-trading#3]
Ever since I started using this model, I have been printing money 💰  from my trading setup.

Not sure if there's a code fix for this, but I don't know what they want from me; it's like the more money we come across, the more problems we see?

**Comment by AaruranLog** [comment]
My advice to you is to ensure that your big earnings do not become small, because as a wise philosopher once said: "Damn right I like the life I live because I went from negative to positive."
